version: "2.4"

services:
  db:
    image: mysql:9.5.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: BalerDB
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - BalerDB:/var/lib/mysql
    ports:
      - "59972:3306"
    mem_limit: 500m
    mem_reservation: 450m
    networks:
      - proxy-redirect

  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    mem_limit: 150m
    mem_reservation: 130m
    networks:
      - proxy-redirect

  data-ingest:
    image: database-ingest:0.0.1
    container_name: data-ingest
    restart: always
    depends_on:
      - db
    volumes:
      - ./cfg-data:/app/cfg-data
    mem_limit: 300m
    mem_reservation: 250m
    networks:
      - proxy-redirect

volumes:
  BalerDB:

networks:
  proxy-redirect:
    external: true
    name: proxy-redirect