services:
  db:
    image: mysql:9.5.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: BalerDB
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - BalerDB:/var/lib/mysql
    ports:
      - "59972:3306"
    networks:
      - proxy-redirect

  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - "8080:8080"
    networks:
      - proxy-redirect

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    networks:
      - proxy-redirect

  data-ingest:
    build: ./src
    depends_on:
      db:
        condition: service_started
      mqtt:
        condition: service_started
    volumes:
      - ./cfg-data/:/app/cfg-data/
    restart: always
    networks:
      - proxy-redirect

volumes:
  BalerDB:

networks:
  proxy-redirect:
    external: true
    name: proxy-redirect